//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCMigrator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConvertConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConvertConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCMigrator.Properties.ConvertConfig", typeof(ConvertConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bv_type={0}.
        /// </summary>
        public static string bv_type {
            get {
                return ResourceManager.GetString("bv_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bvr_precise={0}.
        /// </summary>
        public static string bvr_percise {
            get {
                return ResourceManager.GetString("bvr_percise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bvr_type={0}.
        /// </summary>
        public static string bvr_type {
            get {
                return ResourceManager.GetString("bvr_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CsvReader]escape_char=&quot;{0}&quot;.
        /// </summary>
        public static string csv_escape {
            get {
                return ResourceManager.GetString("csv_escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CsvReader]quote=&quot;{0}&quot;.
        /// </summary>
        public static string csv_quote {
            get {
                return ResourceManager.GetString("csv_quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CsvReader]sep=&quot;{0}&quot;.
        /// </summary>
        public static string csv_seperator {
            get {
                return ResourceManager.GetString("csv_seperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to encoding={0}.
        /// </summary>
        public static string file_encoding {
            get {
                return ResourceManager.GetString("file_encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GMS_txcml_string_separator=&quot;{0}&quot;.
        /// </summary>
        public static string gms_sep {
            get {
                return ResourceManager.GetString("gms_sep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grouping={0}.
        /// </summary>
        public static string group_items {
            get {
                return ResourceManager.GetString("group_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to island_batch_size={0}.
        /// </summary>
        public static string island_batch_size {
            get {
                return ResourceManager.GetString("island_batch_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local_time_zome={0}.
        /// </summary>
        public static string local_time {
            get {
                return ResourceManager.GetString("local_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lov_validate={0}.
        /// </summary>
        public static string lov_validate {
            get {
                return ResourceManager.GetString("lov_validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save_gsid_out={0}.
        /// </summary>
        public static string save_gsid {
            get {
                return ResourceManager.GetString("save_gsid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exist={0}.
        /// </summary>
        public static string skip_exists {
            get {
                return ResourceManager.GetString("skip_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source_site={0}.
        /// </summary>
        public static string source_site {
            get {
                return ResourceManager.GetString("source_site", resourceCulture);
            }
        }
    }
}
