//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCMigration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OracleStatements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OracleStatements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCMigration.OracleStatements", typeof(OracleStatements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM COLUMNTOHEADER.
        /// </summary>
        public static string GetColumnMap {
            get {
                return ResourceManager.GetString("GetColumnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM {0}COLUMNTOHEADER.
        /// </summary>
        public static string GetColumnMapWithPrefix {
            get {
                return ResourceManager.GetString("GetColumnMapWithPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM PREFIXJUNCTION.
        /// </summary>
        public static string GetColumnPrefix {
            get {
                return ResourceManager.GetString("GetColumnPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM {0}PREFIXJUNCTION.
        /// </summary>
        public static string GetColumnPrefixWithPrefix {
            get {
                return ResourceManager.GetString("GetColumnPrefixWithPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT column_name FROM DBA_TAB_COLS WHERE table_name = &apos;{0}&apos;.
        /// </summary>
        public static string GetTableColumns {
            get {
                return ResourceManager.GetString("GetTableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT table_name FROM all_tables.
        /// </summary>
        public static string GetTables {
            get {
                return ResourceManager.GetString("GetTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT table_name FROM all_tables where table_name like &apos;%{0}%&apos;.
        /// </summary>
        public static string GetTablesWithPrefix {
            get {
                return ResourceManager.GetString("GetTablesWithPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER BY {0} ASC.
        /// </summary>
        public static string OrderByAscending {
            get {
                return ResourceManager.GetString("OrderByAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER BY {0} DESC.
        /// </summary>
        public static string OrderByDescending {
            get {
                return ResourceManager.GetString("OrderByDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM {0}.
        /// </summary>
        public static string SelectAllData {
            get {
                return ResourceManager.GetString("SelectAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select{0} FROM {1}.
        /// </summary>
        public static string SelectSpecificColumns {
            get {
                return ResourceManager.GetString("SelectSpecificColumns", resourceCulture);
            }
        }
    }
}
